<?php

return [
    'modules_root' => 'modules',
    'modules_namespace' => 'Modules',
    'app' => [
        'controllers' => 'app/Controllers',
        'http' => 'app/Http',
        'injectable' => ['app/Services', 'app/Listeners'],
        'migrations' => 'app/Database/Migrations',
        'views' => 'app/UI/views',
        'components' => 'app/UI/views/components',
        'events' => 'app/Events',
        'tests' => 'app/tests',
        'models' => 'app/Models',
        'dto' => 'app/Dto',
        'seeders' => 'app/Database/Seeders',
        'middlewares' => ['app/Middlewares', 'app/Http/Middlewares', 'app/Controllers/Middlewares'],
        'languages' => 'app/Common/Languages',
        'support' => 'app/Support',
        'templates' => 'app/Common/Templates',
        'includes' => [
            'app/Support/helpers.php',
        ],
        'commands' => [],
    ],
    'modules' => [
        'controllers' => 'src/Controllers',
        'http' => 'src/Http',
        'injectable' => ['src/Services', 'src/Listeners', 'src/Providers'],
        'migrations' => 'src/Database/Migrations',
        'views' => 'src/UI/views',
        'components' => 'src/UI/views/components',
        'commands' => 'src/Commands',
        'events' => 'src/Events',
        'tests' => 'src/tests',
        'models' => 'src/Models',
        'dto' => 'src/Dto',
        'seeders' => 'src/Database/Seeders',
        'middlewares' => ['src/Middlewares', 'src/Http/Middlewares', 'src/Controllers/Middlewares'],
        'languages' => 'src/Languages',
        'templates' => 'src/Common/Templates',
    ],
];
