<?php

return [
    'app_root' => 'app',
    'app_namespace' => 'App',
    'app' => [
        'controllers' => 'Controllers',
        'http' => 'Http',
        'injectable' => ['Services', 'Listeners'],
        'migrations' => 'Database/Migrations',
        'assets' => 'UI/assets',
        'views' => 'UI/views',
        'layouts' => 'UI/views/layouts',
        'pages' => 'UI/views/pages',
        'components' => 'UI/views/components',
        'events' => 'Events',
        'tests' => 'tests',
        'models' => 'Models',
        'dto' => 'Dto',
        'seeders' => 'Database/Seeders',
        'middlewares' => ['Middlewares', 'Http/Middlewares', 'Controllers/Middlewares'],
        'languages' => 'Common/Languages',
        'support' => 'Support',
        'templates' => 'Common/Templates',
        'error_pages' => 'Common/error_pages',
        'includes' => [
            'Support/helpers.php',
        ],
        'commands' => [],
    ],
    'modules_root' => ['modules', 'capabilities'],
    'modules_namespace' => ['Modules', 'Capability'],
    'module_entry_files' => ['{name}Module.php', '{name}.php'],
    'module_entry_glob' => '*Module.php',
    'modules' => [
        'controllers' => 'src/Controllers',
        'http' => 'src/Http',
        'injectable' => ['src/Services', 'src/Listeners', 'src/Providers'],
        'migrations' => 'src/Database/Migrations',
        'assets' => 'src/UI/assets',
        'views' => 'src/UI/views',
        'layouts' => 'src/UI/views/layouts',
        'pages' => 'src/UI/views/pages',
        'components' => 'src/UI/views/components',
        'commands' => 'src/Commands',
        'events' => 'src/Events',
        'tests' => 'src/tests',
        'models' => 'src/Models',
        'dto' => 'src/Dto',
        'seeders' => 'src/Database/Seeders',
        'middlewares' => ['src/Middlewares', 'src/Http/Middlewares', 'src/Controllers/Middlewares'],
        'languages' => 'src/Languages',
        'templates' => 'src/Common/Templates',
        'error_pages' => 'src/Common/error_pages',
    ],
];
